### ISSUE TITLE
Not able to reproduce greedy search results with beam_width=1

### ISSUE THREAD

**Issue by ashu5644** [patrickvonplaten/Wav2Vec2_PyCTCDecode#6]
Hi @patrickvonplaten , I am following this tutorial https://huggingface.co/blog/wav2vec2-with-ngram . I have tried with some beam width variations, but getting large WER's compared to greedy search. So, I tried it with passing beam_width=1 in decode function of pyctcdecode but getting similar WER to beam_width = {4,10, default=100}. Is it normal behaviour? I suppose , beam_width=1 should give similar results as of greedy decoding.

**Comment by patrickvonplaten** [comment]
Interesting! To be honest I don't really know what the best beam width is...maybe ask on https://github.com/kensho-technologies/pyctcdecode

**Comment by ashu5644** [comment]
Ok, Thanks. I will check.
